# SPDX-FileCopyrightText: Copyright 2023 Move Agency Group B.V., Zwolle, The Netherlands
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check
on: [push, pull_request]

jobs:
  reuse:
    runs-on: ubuntu-latest
    name: "REUSE Lint"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: REUSE lint
        uses: fsfe/reuse-action@v1
        with:
          args: --include-submodules lint
